linters:
  # Disable all linters.
  # Default: false
  enable-all: true
  # Enable specific linter
  # https://golangci-lint.run/usage/linters/#enabled-by-default
  disable:
    - exportloopref # deprecated
    - execinquery # deprecated
    - gomnd # deprecated
    - wsl
    - mnd
    - varnamelen
    - nlreturn
    - testpackage
    - wrapcheck
    - gochecknoglobals
    - depguard
    - tagalign
    - gofumpt
    - godot
linters-settings:
  exhaustive:
    ignore-enum-types: "reflect.Kind"
