// Code generated by "stringer -type=MyEnum"; DO NOT EDIT.

package basics

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Apple-1]
	_ = x[Banana-2]
	_ = x[PineApple-3]
}

const _MyEnum_name = "AppleBananaPineApple"

var _MyEnum_index = [...]uint8{0, 5, 11, 20}

func (i MyEnum) String() string {
	i -= 1
	if i < 0 || i >= MyEnum(len(_MyEnum_index)-1) {
		return "MyEnum(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _MyEnum_name[_MyEnum_index[i]:_MyEnum_index[i+1]]
}
